version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: feiraslondrina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  back:
    build: ./back
    environment:
      DB_URL: jdbc:postgresql://db:5432/feiraslondrina
      DB_USERNAME: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  front:
    build: ./front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - back
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"
    depends_on:
      - front
    restart: unless-stopped

volumes:
  db_data:
