package com.securitygateway.loginboilerplate.model.property.enums;

public enum PropertyItem {
    AREA_DE_SERVICO,
    ARMARIOS,
    BANHEIRO_DE_SERVICO,
    BANHEIRO_SOCIAL,
    BAR,
    CHURRASQUEIRA,
    COZINHA_PLANEJADA,
    DEPENDENCIA_DE_SERVICOS,
    DESPENSA,
    DORMITORIOS_COM_ARMARIOS,
    LAVABO,
    SACADA,
    SALA_DE_TV,
    VISTA_PANORAMICA,
    // adicionais
    HIDROMASSAGEM,
    AR_CONDICIONADO,
    LAREIRA,
    ARMARIOS_PLANEJADOS,
    BOX_EM_VIDRO,
    HALL_DE_ENTRADA,
    SACADA_COM_CHURRASQUEIRA,
    SALA_DE_ESTAR,
    SUITE_MASTER,
    VARANDA
}
