export enum Finalidade {
  RESIDENCIAL = 'RESIDENCIAL',
  COMERCIAL = 'COMERCIAL',
  MISTO = 'MISTO'
}

export enum PropertyType {
  APARTAMENTO = 'APARTAMENTO',
  CASA = 'CASA',
  COMERCIAL = 'COMERCIAL',
  RURAL = 'RURAL',
  TERRENO = 'TERRENO'
}

export enum PropertySubtype {
  COBERTURA = 'COBERTURA',
  PADRAO_AP = 'PADRAO_AP',
  SOBRELOJA_AP = 'SOBRELOJA_AP',
  CASA_DE_FUNDOS = 'CASA_DE_FUNDOS',
  CHACARA_CASA = 'CHACARA_CASA',
  COMERCIAL_CASA = 'COMERCIAL_CASA',
  CONDOMINIO = 'CONDOMINIO',
  CASA_PADRAO = 'CASA_PADRAO',
  BARRACAO = 'BARRACAO',
  CONJUNTO_COMERCIAL = 'CONJUNTO_COMERCIAL',
  EMPREENDIMENTO = 'EMPREENDIMENTO',
  GALPAO = 'GALPAO',
  IMOVEL_COMERCIAL = 'IMOVEL_COMERCIAL',
  LOJA = 'LOJA',
  PONTO = 'PONTO',
  SALA = 'SALA',
  SALA_COMERCIAL_EDIFICIO = 'SALA_COMERCIAL_EDIFICIO',
  SOBRELOJA_COM = 'SOBRELOJA_COM',
  CHACARA_RURAL = 'CHACARA_RURAL',
  TERRENO_COMERCIAL = 'TERRENO_COMERCIAL',
  TERRENO_PADRAO = 'TERRENO_PADRAO'
}

export enum PropertyItemEnum {
  AREA_DE_SERVICO = 'AREA_DE_SERVICO',
  ARMARIOS = 'ARMARIOS',
  BANHEIRO_DE_SERVICO = 'BANHEIRO_DE_SERVICO',
  BANHEIRO_SOCIAL = 'BANHEIRO_SOCIAL',
  BAR = 'BAR',
  CHURRASQUEIRA = 'CHURRASQUEIRA',
  COZINHA_PLANEJADA = 'COZINHA_PLANEJADA',
  DEPENDENCIA_DE_SERVICOS = 'DEPENDENCIA_DE_SERVICOS',
  DESPENSA = 'DESPENSA',
  DORMITORIOS_COM_ARMARIOS = 'DORMITORIOS_COM_ARMARIOS',
  LAVABO = 'LAVABO',
  SACADA = 'SACADA',
  SALA_DE_TV = 'SALA_DE_TV',
  VISTA_PANORAMICA = 'VISTA_PANORAMICA',
  HIDROMASSAGEM = 'HIDROMASSAGEM',
  AR_CONDICIONADO = 'AR_CONDICIONADO',
  LAREIRA = 'LAREIRA'
}

export enum BuildingItemEnum {
  ELEVADOR = 'ELEVADOR',
  ACADEMIA = 'ACADEMIA',
  PISCINA = 'PISCINA',
  AREA_GOURMET = 'AREA_GOURMET',
  SALAO_DE_FESTAS = 'SALAO_DE_FESTAS',
  PORTARIA_24H = 'PORTARIA_24H'
}
